#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N missingData
#
# Send an email after the job has finished
#$ -m e
#$ -M correo@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
# Write your commands in the next line
cd /mnt/Citosina/amedina/ecoss/claseRNASeq2023/data/

wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/094/SRR12363094/SRR12363094_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/094/SRR12363094/SRR12363094_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/000/SRR12363100/SRR12363100_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/000/SRR12363100/SRR12363100_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/097/SRR12363097/SRR12363097_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/097/SRR12363097/SRR12363097_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/003/SRR12363103/SRR12363103_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/003/SRR12363103/SRR12363103_2.fastq.gz
