#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N control_2
#
# Send an email after the job has finished
#$ -m e
#$ -M diego.rames@me.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:

#
# Write your commands in the next line
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/093/SRR12363093/SRR12363093_1.fastq.gz;
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/093/SRR12363093/SRR12363093_2.fastq.gz
