#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N sampleData
#
# Send an email after the job has finished
#$ -m e
#$ -M correo@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
# Write your commands in the next line
cd /mnt/Citosina/amedina/ecoss/claseRNASeq2023/data/

wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/096/SRR12363096/SRR12363096_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/096/SRR12363096/SRR12363096_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/099/SRR12363099/SRR12363099_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/099/SRR12363099/SRR12363099_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/002/SRR12363102/SRR12363102_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/002/SRR12363102/SRR12363102_2.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/093/SRR12363093/SRR12363093_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/093/SRR12363093/SRR12363093_2.fastq.gz
