#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N LPS_4h
#
# Send an email after the job has finished
#$ -m e
#$ -M correo@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:

#
# Write your commands in the next line
wget -P /mnt/Citosina/amedina/dramirez/clase/data/PLS_4h ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/002/SRR12363102/SRR12363102_1.fastq.gz;
wget -P /mnt/Citosina/amedina/dramirez/clase/data/PLS_4h ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR123/002/SRR12363102/SRR12363102_2.fastq.gz
